pipeline:
  identifier: Build_task_repo_1684150822711
  name: Build task-repo
  orgIdentifier: default
  projectIdentifier: githubtask
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: UnitedSCM
                    repoName: task-repo
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |
                      #!/bin/bash

                      # Install jq if necessary

                      sudo apt-get install jq -y
                      sudo apt-get upgrade -y
                      sudo apt-get update -y
                      gh --version


                      #cd shivakumar123441/task-repo/

                      # Read the JSON file content
                      fileContent=$(cat task-repo/json.file)

                      # Check the value of "a" and update if necessary
                      if [[ $(echo "$fileContent" | jq -r '.a') != "1" ]]; then
                        fileContent=$(echo "$fileContent" | jq '.a = "1"')
                      fi

                      # Check the presence of "b" and add if necessary
                      if [[ $(echo "$fileContent" | jq -r 'has("b")') == "false" ]]; then
                        fileContent=$(echo "$fileContent" | jq '.b = "1"')
                      fi

                      # Write the modified content back to the JSON file
                      echo "$fileContent" > task-repo/json.file

                      # Stage the modified JSON file
                      cd task-repo/
                      username="shivakumar123441"
                      token="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"
                      git config --global user.name $username
                      git remote set-url origin https://$username:$token@github.com/$username/task-repo.git
                      echo -e "$token\n" | gh auth login --with-token

                      git add .

                      # Commit the changes
                      git commit -m "Update JSON file"

                      # Push the changes back to the repository
                      git push
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
