pipeline:
  identifier: Build_task_repo_1684150822711
  name: Build task-repo
  orgIdentifier: default
  projectIdentifier: githubtask
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone
                  identifier: GitClone_1
                  spec:
                    connectorRef: UnitedSCM
                    repoName: task-repo
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Run
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |-
                      #!/bin/bash

                      # GitHub repository details
                      GITHUB_REPO="task-repo"
                      GITHUB_TOKEN="<+pipeline.stages.Build.variables.task123>"

                      # Docker service details
                      SERVICE_NAME="docker"

                      # Install Docker
                      curl -fsSL https://get.docker.com -o get-docker.sh
                      sudo sh get-docker.sh

                      # Start Docker service
                      sudo systemctl start docker

                      # Check Docker version
                      DOCKER_VERSION=$(docker --version | awk '{print $3}')

                      # Create JSON payload
                      JSON_PAYLOAD="{ \"service\": \"$SERVICE_NAME\", \"version\": \"$DOCKER_VERSION\" }"

                      # Create temporary file for JSON payload
                      JSON_FILE=$(mktemp)
                      echo "$JSON_PAYLOAD" > "$JSON_FILE"
                      echo "$JSON_FILE" > task-repo/json.file
                      cd task-repo/
                      username="shivakumar123441"
                      git remote set-url origin https://$username:<+pipeline.stages.Build.variables.task123>@github.com/$username/task-repo.git

                      git add .

                      # Commit the changes
                      git commit -m "Service JSON file"

                      # Push the changes back to the repository
                      git push -u origin main

                      # Push JSON file to GitHub repository
                      #curl -X PUT -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/json" --data-binary "@$JSON_FILE" "https://api.github.com/repos/$GITHUB_REPO/json.file"

                      # Cleanup temporary file
                      rm "$JSON_FILE"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        variables:
          - name: task123
            type: Secret
            description: ""
            value: HarnessPATGIT
