pipeline:
  identifier: Build_task_repo_1684150822711
  name: Build task-repo
  orgIdentifier: default
  projectIdentifier: githubtask
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone
                  identifier: GitClone_1
                  spec:
                    connectorRef: UnitedSCM
                    repoName: task-repo
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Run
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |
                      #!/bin/bash

                      # Step 1: Linux server (already assumed to be present)
                      sudo apt-get install jq wget curl unzip -y
                      sudo apt-get update -y

                      # Step 2: Install the service using Docker
                      service_name="<+pipeline.stages.Build.variables.service>"
                      service_tag="<+pipeline.stages.Build.variables.tag>"

                      # Pull the Docker image
                      docker pull "$service_name":"$service_tag"

                      # Run the Docker container
                      docker run -d --name "$service_name" "$service_name":"$service_tag"

                      # Step 3: Fetch the service name and its tag
                      installed_service_name="$service_name"
                      installed_service_tag="$service_tag"

                      # Step 4: Check if the service name and tag exist in the file on GitHub
                      # GitHub repository details
                      github_repo="task-repo"
                      github_token="<+pipeline.stages.Build.variables.task123>"
                      username="shivakumar123441"
                      cd /harness/task-repo/
                      file_content=$(cat /harness/task-repo/json.file)

                      # Check if the service name and tag exist in the file
                      if [[ "$file_content" == *"$installed_service_name"* ]] && [[ "$file_content" == *"$installed_service_tag"* ]]; then
                        echo "Service and tag already exist in the file on GitHub."
                      else
                        # Update or add the service name and tag to the file
                        updated_content=echo '[{"service": "<+pipeline.stages.Build.variables.service>", "tag": "<+pipeline.stages.Build.variables.tag>"}]' | jq '. + [{"service": "<+pipeline.stages.Build.variables.service>", "tag": "<+pipeline.stages.Build.variables.tag>"}]'
                      fi
                      echo "$updated_content" > /harness/task-repo/json.file
                      git remote set-url origin https://$username:$github_token@github.com/$username/task-repo.git
                      git add .

                      # Commit the changes
                      git commit -m "Update JSON file"

                      # Push the changes back to the repository
                      git push -u origin main
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        variables:
          - name: task123
            type: Secret
            description: ""
            value: HarnessPATGIT
          - name: service
            type: String
            description: ""
            value: nginx
          - name: tag
            type: String
            description: ""
            value: latest
